services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    expose:
      - 8000
    volumes:
      - ./backend:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/nginx/certs

volumes:
  postgres_data:
    name: rhythmix_db
    driver: local
  certs:
