services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  frontend:
    image: node:18.18.0-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure

  postgres:
    image: postgres:15.5-alpine
    volumes:
      - rhythmix_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none

volumes:
    rhythmix_data: {}
