# Generated by Django 4.2.13 on 2024-11-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-id',), 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
